### ISSUE TITLE
Changing the color of vectors

### ISSUE THREAD

**Issue by cassioseffrin** [seekshiva/react-native-remote-svg#2]
Hi seekshiva,

First, congrats for your awesome job in this library. I think your approach for svg icons is the best and the easiest.

I don't think my question is an issue. However,  I can't find a way to change the color of the icon. The default image doesn't have this prop. Maybe it's just my mistake, could you give me a help?

Best Regards!

**Comment by seekshiva** [comment]
Hi @cassioseffrin,

You can convert a set of svg images to font files using [these techniques](https://stackoverflow.com/questions/13278707/how-to-convert-svg-files-to-a-font#35092005). Since these are just fonts, you can set `color` in style prop to set the icon color.

Additionally, you can use `react-native-vector-icons` to define a glyphMap so that you can use it like this:

```
<Icon name="rocket" size={30} color="#900" />
```

In glyphMap, you will be defining the mapping between icon name (eg: 'rocket') to the exact character in font that will render that icon.

More info on how to define custom fonts with react-native-vector-icons [here](https://github.com/oblador/react-native-vector-icons#custom-fonts).

**Comment by cassioseffrin** [comment]
@seekshiva Thanks for the suggestions, I liked them all!
