### ISSUE TITLE
SVG renders completely different than Image

### ISSUE THREAD

**Issue by fullhdpixel** [seekshiva/react-native-remote-svg#6]
Reproduction repo:

https://github.com/fullhdpixel/stopwatch_RN/tree/svg-problem

iOS Emulator SVG from 'react-native-remote-svg'
![image](https://user-images.githubusercontent.com/7371397/36924468-f675ef6e-1e6e-11e8-8a1d-335f20e9b827.png)

Android phone SVG from 'react-native-remote-svg'
![image](https://user-images.githubusercontent.com/7371397/36924501-1087fac8-1e6f-11e8-8d76-5eef5538a98d.png)

iOS Emulator Image from 'react-native'
![image](https://user-images.githubusercontent.com/7371397/36924511-21227f02-1e6f-11e8-8ae0-87fe48c0fe4c.png)

Android phone Image is same as iOS Emulator Image

**Comment by seekshiva** [comment]
Hi @fullhdpixel,

Thanks for the reproduction repo.

React native requires you to define {width, height} of an image according to the image's aspect ratio. If you take a 100x100 image and give it `style={{ width: 100, height: 50 }}`, the image won't be scaled and displayed like in web. You will merely see the center part of the image. This is true for both images loaded locally and via remote uri. Demo to prove this: https://snack.expo.io/HJAz9h6dz

<img width="375" alt="image 2" src="https://user-images.githubusercontent.com/484349/37113238-d375e42e-226a-11e8-85a0-62e6ee69534e.png">

---

In your code, you had specified the height of the image to be 55% of screen height and width to be 100% of screen width. Aspect ratio of mobile devices would vary, and the width/height that get set would not match the aspect ratio of the image.

I would suggest you to use px values like this rather than %

<img width="978" alt="screen shot 2018-03-08 at 12 54 14 am" src="https://user-images.githubusercontent.com/484349/37113426-5908cb60-226b-11e8-991a-b0d92e10723b.png">

In the above code sets image width to device width, and calculates image height dynamically.

The above code got it working in different screen sizes.

**Comment by fullhdpixel** [comment]
Thanks @seekshiva, it works!
